### ISSUE TITLE
pb utilisation mspt

### ISSUE THREAD

**Issue by LaraGales** [llegregam/PascalTriangle#1] opened 2024-06-11 12:48 UTC
Bonjour Loic 
Je n'arrive tjs a faire tourner mspt
![Sans titre](https://github.com/llegregam/PascalTriangle/assets/172395525/7662de46-65e9-4923-8ee6-818511fa362d)
merci 
lara

**Comment by llegregam** [comment] 2024-06-20 08:45
Couldn't reproduce, closing the issue

**Closed as completed by llegregam** 2024-06-20 08:45 UTC
Labels: bug
